import {
  pgTable,
  text,
  timestamp,
  boolean,
  integer,
  pgEnum,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { relations, sql } from "drizzle-orm";

/**
 * Barangay Sagayad — database schema (Drizzle ORM / PostgreSQL)
 *
 * Conventions:
 * - Every table has a UUID primary key generated by Postgres (gen_random_uuid()).
 * - createdAt / updatedAt are set automatically.
 * - deletedAt is used for soft deletion on content tables (never hard-delete
 *   official records, requests, or reports — they're part of the public record
 *   or an audit trail).
 * - Enums encode workflows explicitly so invalid states are impossible at the
 *   database level, not just enforced in application code.
 */

const id = () =>
  text("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`);

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
};

// ---------------------------------------------------------------------------
// Roles & Users (admin dashboard authentication / RBAC)
// ---------------------------------------------------------------------------

export const roleEnum = pgEnum("role", [
  "super_admin",
  "punong_barangay",
  "secretary",
  "treasurer",
  "health_personnel",
  "education_admin",
  "project_manager",
  "sk_admin",
  "purok_coordinator",
  "viewer",
]);

export const users = pgTable(
  "users",
  {
    id: id(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    passwordHash: text("password_hash").notNull(),
    role: roleEnum("role").notNull().default("viewer"),
    isActive: boolean("is_active").notNull().default(true),
    lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [uniqueIndex("users_email_idx").on(table.email)]
);

// ---------------------------------------------------------------------------
// Site settings — singleton row of editable global content
// (contact info, tagline, population figure, emergency banner, etc.)
// Kept as one row rather than key/value pairs so the admin UI can be a single
// settings form instead of a generic key/value editor.
// ---------------------------------------------------------------------------

export const siteSettings = pgTable("site_settings", {
  id: id(),
  barangayName: text("barangay_name").notNull().default("Barangay Sagayad"),
  tagline: text("tagline")
    .notNull()
    .default("Serbisyo, Impormasyon, at Pakikilahok Para sa Lahat."),
  municipality: text("municipality").notNull().default("City of San Fernando"),
  province: text("province").notNull().default("La Union"),
  region: text("region").notNull().default("Region I"),
  address: text("address"), // null = "To be updated" in the UI
  telephone: text("telephone"),
  mobile: text("mobile"),
  email: text("email"),
  officeHours: text("office_hours"),
  facebookUrl: text("facebook_url"),
  captainFacebookUrl: text("captain_facebook_url"),
  population: integer("population"),
  populationYear: integer("population_year"),
  households: integer("households"),
  emergencyBannerActive: boolean("emergency_banner_active").notNull().default(false),
  emergencyBannerLevel: text("emergency_banner_level").default("info"), // info | watch | warning | red_alert
  emergencyBannerMessage: text("emergency_banner_message"),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// Officials — Punong Barangay, Kagawad, SK, and support personnel
// ---------------------------------------------------------------------------

export const officialCategoryEnum = pgEnum("official_category", [
  "punong_barangay",
  "kagawad",
  "sk_official",
  "personnel", // secretary, treasurer, BHW, midwife, tanod, lupon, etc.
]);

export const officials = pgTable(
  "officials",
  {
    id: id(),
    name: text("name").notNull(),
    position: text("position").notNull(),
    category: officialCategoryEnum("category").notNull(),
    committee: text("committee"),
    responsibilities: text("responsibilities"),
    availability: text("availability"),
    contactEmail: text("contact_email"),
    contactPhone: text("contact_phone"),
    photoUrl: text("photo_url"),
    sortOrder: integer("sort_order").notNull().default(0),
    isActive: boolean("is_active").notNull().default(true),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [index("officials_category_idx").on(table.category)]
);

// ---------------------------------------------------------------------------
// Puroks — intentionally seeded empty. The product spec explicitly says not
// to invent Purok data; every field here is admin-entered.
// ---------------------------------------------------------------------------

export const puroks = pgTable("puroks", {
  id: id(),
  number: text("number").notNull(), // e.g. "1", "2A" — text because numbering isn't always purely numeric
  name: text("name"),
  description: text("description"),
  leaderName: text("leader_name"),
  leaderContact: text("leader_contact"),
  population: integer("population"),
  households: integer("households"),
  facilities: text("facilities"), // freeform for Phase 1; can normalize into a join table later
  photoUrl: text("photo_url"),
  isActive: boolean("is_active").notNull().default(true),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// Announcements
// ---------------------------------------------------------------------------

export const announcementCategoryEnum = pgEnum("announcement_category", [
  "emergency",
  "government",
  "health",
  "education",
  "senior",
  "youth",
  "public_works",
  "peace_and_order",
  "environment",
  "livelihood",
  "events",
]);

export const announcementStatusEnum = pgEnum("announcement_status", ["draft", "published"]);

export const announcements = pgTable(
  "announcements",
  {
    id: id(),
    title: text("title").notNull(),
    slug: text("slug").notNull(),
    category: announcementCategoryEnum("category").notNull(),
    body: text("body").notNull(),
    imageUrl: text("image_url"),
    location: text("location"),
    isPinned: boolean("is_pinned").notNull().default(false),
    status: announcementStatusEnum("status").notNull().default("draft"),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    authorId: text("author_id").references(() => users.id, { onDelete: "set null" }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("announcements_slug_idx").on(table.slug),
    index("announcements_status_idx").on(table.status),
  ]
);

// ---------------------------------------------------------------------------
// Services — the "quick services" grid + document types that feed the
// (Phase 2) document request workflow. Fees / requirements / processing time
// are all admin-editable rather than hard-coded, per spec.
// ---------------------------------------------------------------------------

export const serviceCategoryEnum = pgEnum("service_category", [
  "document",
  "report",
  "health",
  "education",
  "senior",
  "youth",
  "general",
]);

export const services = pgTable(
  "services",
  {
    id: id(),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    category: serviceCategoryEnum("category").notNull(),
    description: text("description"),
    feeInfo: text("fee_info"), // null = "To be updated"
    requirements: text("requirements"),
    processingTime: text("processing_time"),
    icon: text("icon"), // lucide-react icon name
    isRequestable: boolean("is_requestable").notNull().default(false), // true once the online request flow is wired up
    sortOrder: integer("sort_order").notNull().default(0),
    isActive: boolean("is_active").notNull().default(true),
    ...timestamps,
  },
  (table) => [uniqueIndex("services_slug_idx").on(table.slug)]
);

// ---------------------------------------------------------------------------
// Generic CMS pages (Captain's Message, About, Privacy Policy, etc.)
// ---------------------------------------------------------------------------

export const pages = pgTable(
  "pages",
  {
    id: id(),
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    content: text("content").notNull().default(""),
    photoUrl: text("photo_url"),
    ...timestamps,
  },
  (table) => [uniqueIndex("pages_slug_idx").on(table.slug)]
);

// ---------------------------------------------------------------------------
// Forward-looking tables (schema defined now for architecture correctness;
// admin UI and public workflow ship in Phase 2). Having these in place from
// day one means Phase 2 is additive — no schema churn on live data.
// ---------------------------------------------------------------------------

export const requestStatusEnum = pgEnum("request_status", [
  "submitted",
  "under_review",
  "approved",
  "ready_for_pickup",
  "released",
]);

export const documentRequests = pgTable(
  "document_requests",
  {
    id: id(),
    trackingNumber: text("tracking_number").notNull(),
    serviceId: text("service_id").references(() => services.id),
    requesterName: text("requester_name").notNull(),
    requesterContact: text("requester_contact").notNull(),
    purpose: text("purpose"),
    purokId: text("purok_id").references(() => puroks.id),
    status: requestStatusEnum("status").notNull().default("submitted"),
    notes: text("notes"),
    submittedAt: timestamp("submitted_at", { withTimezone: true }).defaultNow().notNull(),
    releasedAt: timestamp("released_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [uniqueIndex("document_requests_tracking_idx").on(table.trackingNumber)]
);

export const reportStatusEnum = pgEnum("report_status", [
  "received",
  "under_review",
  "assigned",
  "in_progress",
  "resolved",
  "closed",
]);

export const reports = pgTable(
  "reports",
  {
    id: id(),
    referenceNumber: text("reference_number").notNull(),
    category: text("category").notNull(),
    description: text("description").notNull(),
    location: text("location"),
    purokId: text("purok_id").references(() => puroks.id),
    photoUrl: text("photo_url"),
    isAnonymous: boolean("is_anonymous").notNull().default(false),
    contactName: text("contact_name"),
    contactPhone: text("contact_phone"),
    status: reportStatusEnum("status").notNull().default("received"),
    assignedToId: text("assigned_to_id").references(() => users.id),
    ...timestamps,
  },
  (table) => [uniqueIndex("reports_reference_idx").on(table.referenceNumber)]
);

export const events = pgTable("events", {
  id: id(),
  title: text("title").notNull(),
  description: text("description"),
  category: text("category"),
  startAt: timestamp("start_at", { withTimezone: true }).notNull(),
  endAt: timestamp("end_at", { withTimezone: true }),
  location: text("location"),
  isPublished: boolean("is_published").notNull().default(false),
  ...timestamps,
});

export const schedules = pgTable("schedules", {
  id: id(),
  type: text("type").notNull(), // midwife | bhw | vaccination | medical_mission | dental | other
  title: text("title").notNull(),
  provider: text("provider"),
  days: text("days"), // e.g. "Mon, Wed, Fri"
  hours: text("hours"),
  location: text("location"),
  servicesOffered: text("services_offered"),
  isWalkIn: boolean("is_walk_in").notNull().default(true),
  isActive: boolean("is_active").notNull().default(true),
  ...timestamps,
});

export const schools = pgTable("schools", {
  id: id(),
  name: text("name").notNull(),
  level: text("level"), // preschool | elementary | high_school
  address: text("address"),
  headName: text("head_name"),
  contact: text("contact"),
  description: text("description"),
  isActive: boolean("is_active").notNull().default(true),
  ...timestamps,
});

export const mediaAssets = pgTable("media_assets", {
  id: id(),
  url: text("url").notNull(),
  altText: text("alt_text"),
  uploadedById: text("uploaded_by_id").references(() => users.id),
  ...timestamps,
});

export const emergencyContacts = pgTable("emergency_contacts", {
  id: id(),
  label: text("label").notNull(), // e.g. "Police (PNP)", "City DRRMO"
  phone: text("phone"),
  email: text("email"),
  notes: text("notes"), // e.g. "Local 7005100" when a number isn't a direct line
  sourceUrl: text("source_url"), // where this was verified, for staff to re-check later
  sortOrder: integer("sort_order").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
  ...timestamps,
});

export const contactMessages = pgTable("contact_messages", {
  id: id(),
  name: text("name").notNull(),
  contact: text("contact").notNull(), // email or phone
  subject: text("subject"),
  message: text("message").notNull(),
  isRead: boolean("is_read").notNull().default(false),
  ...timestamps,
});

export const auditLogs = pgTable("audit_logs", {
  id: id(),
  userId: text("user_id").references(() => users.id),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id"),
  metadata: text("metadata"), // JSON-encoded string
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// ---------------------------------------------------------------------------
// Relations
// ---------------------------------------------------------------------------

export const usersRelations = relations(users, ({ many }) => ({
  announcements: many(announcements),
  assignedReports: many(reports),
}));

export const announcementsRelations = relations(announcements, ({ one }) => ({
  author: one(users, { fields: [announcements.authorId], references: [users.id] }),
}));

export const puroksRelations = relations(puroks, ({ many }) => ({
  documentRequests: many(documentRequests),
  reports: many(reports),
}));

export const servicesRelations = relations(services, ({ many }) => ({
  documentRequests: many(documentRequests),
}));
